// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS5k2QsaQhi5RLU_N8RYLvzInTWb9NHYQ',
    appId: '1:475127308937:android:8311976322025beb1a1c58',
    messagingSenderId: '475127308937',
    projectId: 'fisuq-app',
    storageBucket: 'fisuq-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgLg9dYejhcL3SzNwMefk7Gojej_99ug',
    appId: '1:475127308937:ios:7cc3cd60d22f9bf31a1c58',
    messagingSenderId: '475127308937',
    projectId: 'fisuq-app',
    storageBucket: 'fisuq-app.appspot.com',
    androidClientId: '475127308937-es9mabu1af5cbesoko5sov68g2nmk8de.apps.googleusercontent.com',
    iosClientId: '475127308937-rdpchlgsp8n4o147lubggqfhh8ouseuk.apps.googleusercontent.com',
    iosBundleId: 'com.fisuq.vendor',
  );
}
